import { config } from "dotenv";

// AQUI CAMBIO EL LUGAR A DONDE APUNTAN LAS VARAIBLES DE ENTORNO PARA QUE AHORA TOME EL ARCHIVO .ENV.TEST
// ESTO ES IMPORTANTE PORQUE EN ARCHIVO .ENV TIENE UNA URL DE BASE DE DATOS DIFERENTE PARA TESTING Y EL PUERTO TAMBIEN ES DIFERENTE PARA
config({
    path: ".env.test"
})